name: Tableau Workbook Workflows Staging
on:
  workflow_dispatch:
jobs:
  tableau-validation-action:
    name: Tableau Workbook Staging Publisher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Tableau Workbook Action' 
        uses: jayamanikharyono/tableau-workbook-action@v1.4
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SITE_ID: ${{ secrets.SITE_ID }}
          TABLEAU_URL: ${{ secrets.TABLEAU_URL }}
        with:
          workbook_dir: tests/workbooks
          env: staging
          repo_token: ${{ secrets.GITHUB_TOKEN }}
