name: Testing

on:
 workflow_dispatch:

   inputs:
     test:
       type: number
       description: 'Testing Number'
       required: true
     

jobs:
 release_deploy:
   name: release deploy
   runs-on: ubuntu-latest
   
   steps:
     - name: Print
       run: echo "value ${{ github.event.inputs.test }}"
