name: IO(Heroku) release deploy

on:
 workflow_dispatch:

   inputs:
     test:
       type: number
       description: '60 second pause between steps'
       required: true
     



jobs:
 release_deploy:
   name: release deploy
   runs-on: ubuntu-latest
   
   steps:
     - name: Print
       run: echo "Hello World"
